config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  # 관리자 URL 패턴 정의
    # path('user/', include('user.urls')),  # user 앱의 URL 패턴
    # path('common/', include('common.urls')),  # common 앱의 URL 패턴
    path('qna/', include('qna.urls')),  # qna 앱의 URL 패턴
    path('welfare1/', include('welfare1.urls')),  # welfare1 앱의 URL 패턴
    #path('main/', include('main.urls')),  # main 앱의 URL 패턴
    path('team/', include('team.urls')),  # team 앱의 URL 패턴
    path('', include('main.urls')),  # 루트 URL을 main 앱으로 포워딩
]

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
    ## 질문 불러오기
    path('', views.index, name='index'),
    ## 질문 상세 조회
    path('<int:question_id>/', views.detail, name='detail'),
    ## 댓글 작성
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    ## 질문 작성
    path('question/create/', views.question_create, name='question_create'),
    ## 댓글 삭제
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

qna/models.py
from django.db import models
from common.models import User

# Create your models here.
"""
 * MODEL No. 1
 * MODEL Name : Question
"""
class Question(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

"""
 * MODEL No. 2
 * MODEL Name : Answer
"""
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

qna/forms.py
from django import forms
from qna.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }  

qna/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Answer, Question
from .forms import QuestionForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q


"""
 * API No. 1
 * API Name : 게시글 불러오기
 * [GET] /questionBoard
"""
def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    #게시글 작성 역순으로 출력
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            # Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'qna/qna_list.html', context)


"""
 * API No. 2
 * API Name : 게시글 상세 조회
 * [GET] /questionBoard/{boardId}
"""
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'qna/qna_detail.html', context)


"""
 * API No. 3
 * API Name : 댓글 작성
 * [POST] /questionBoard/answer/create/{answerID}
"""
@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    content = request.POST.get('content','').strip()
    if content:
        question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now(), author=request.user)
    return redirect('qna:detail', question_id=question.id)


"""
 * API No. 4
 * API Name : 게시글 작성
 * [GET] /questionBoard/question/create
"""
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('qna:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'qna/qna_write.html', context)


"""
 * API No. 6
 * API Name : 댓글 삭제
 * [GET] /questionBoard/answer/delete
"""
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()
    return redirect('qna:detail', question_id=answer.question.id)

templates/qna/qna_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static '/css/qna/qna_detail.css' %}">
</head>

<div class="container my-3 wide-container">
    <!-- 질문 -->
    <a href="{% url 'qna:index' %}" style="text-decoration: none;"><h2>QnA</h2></a>
    <br>
    <div class="date-container">
        <div class="badge bg-light text-dark p-2 date-badge">
            {{ question.create_date }}
        </div>
    </div>
    <div class="card my-3 border-0">
        <div class="card-body">
            <div class="card-text" style="font-weight: bold; font-size: 20px; display: flex;">
                {{ question.id }}
                <div class="card-text" style="padding-left: 30px; padding-right: 25px; flex: 1; word-break: break-all;">
                    {{ question.subject }}
                </div>
            </div>
            <div class="card-text" style="padding: 6px 45px;">{{ question.content }}</div>
        </div>
    </div>
    <br>
    
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2" style="color: #000;"><span style="color: #000">{{question.answer_set.count}}</span>개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="date-container">
        <div class="badge bg-light text-dark p-2 date-badge">
            {{ answer.create_date }}
        </div>
    </div>
    <div class="card my-3 border-0">
        <div class="card-body">
            <div class="card-text" style="display: flex;">
                <span style="font-weight: bold;">운영자</span>
                <div class="card-text" style="padding-left: 30px; padding-right: 25px; flex: 1; word-break: break-all;">
                    {{ answer.content }}
                </div>
            </div>
            <div class="my-3">
                {% if request.user == answer.author %}
                    <a href="#" class="delete btn btn-sm btn-outline-secondary "
                        data-uri="{% url 'qna:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <br>
    <!-- 답변 등록 -->
    {% if user.is_authenticated %}
        <form action="{% url 'qna:answer_create' question.id %}" method="post" class="my-3">
            {% csrf_token %}
            <div class="mb-3">
                <label for="content" class="form-label" style="color: #000000;">답변하기</label>
                <textarea {% if not user.is_authenticated %}disabled{% endif %}
                name="content" id="content" class="form-control" rows="5"></textarea>
            </div>
            <input type="submit" value="답변등록" class="btn btn-outline-light">
        </form>
    {% else %}
    
    {% endif %}
</div>
{% endblock %}

<!-- 질문 삭제 box-->
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("답글을 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/qna/qna_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static '/css/qna/qna.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/qna/qna_list.css' %}">
   
</head>

<div class="container my-3 wide-container">
    <h2>문의 게시판</h2>
    <div class="row my-3 justify-content-between">
        <div class="col-8">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" placeholder="검색어를 입력하세요!" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">검색</button>
                </div>
            </div>
        </div>
        <div class="col-2 text-right">
            <a href="{% url 'qna:question_create' %}" class="btn btn-outline-dark">글쓰기</a>
        </div>
    </div>

    {% if question_list %}
    <div class="list-container">
        <div class="list-header row">
            <div class="col text-center">번호</div>
            <div class="col text-center">제목</div>
            <div class="col text-center">등록일</div>
        </div>
        {% for question in question_list %}
        <div class="list-item row">
            <div class="col text-center">{{ question.id }}</div>
            <div class="col text-left">
                <a href="{% url 'qna:detail' question.id %}">{{ question.subject }}</a>
            </div>
            <div class="col text-center">{{ question.create_date|date:"Y-m-d" }}</div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="text-center">
        {% if q %}
        <p>일치하는 검색 결과가 없습니다.</p>
        {% else %}
        <p>작성된 게시글이 없습니다.</p>
        {% endif %}
    </div>
    {% endif %}

    <!-- Pagination -->
    <div class="container my-3 wide-container">
        <ul class="pagination justify-content-center">
            {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.previous_page_number }}">&lt;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true">&lt;</a>
            </li>
            {% endif %}

            {% for page_number in question_list.paginator.page_range %}
            <li class="page-item {% if page_number == question_list.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endfor %}

            {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.next_page_number }}">&gt;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true">&gt;</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>

<form id="searchForm" method="get" action="{% url 'qna:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.querySelectorAll(".page-link");
page_elements.forEach(element => {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});

const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

templates/qna/qna_write.html
#비밀글

{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static '/css/qna/qna_write.css' %}">
</head>


<div class="container wide-container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-outline-light">저장하기</button>
    </form>
</div>
{% endblock %}