config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  # 관리자 URL 패턴 정의
    # path('user/', include('user.urls')),  # user 앱의 URL 패턴
    # path('common/', include('common.urls')),  # common 앱의 URL 패턴
    path('qna/', include('qna.urls')),  # qna 앱의 URL 패턴
    path('welfare1/', include('welfare1.urls')),  # welfare1 앱의 URL 패턴
    #path('main/', include('main.urls')),  # main 앱의 URL 패턴
    path('team/', include('team.urls')),  # team 앱의 URL 패턴
    path('', include('main.urls')),  # 루트 URL을 main 앱으로 포워딩
]

main/urls.py
# main/urls.py

from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),  # 기본 URL에 대해 views.index 호출
    
]

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
    ## 질문 불러오기
    path('', views.index, name='index'),
    ## 질문 상세 조회
    path('<int:question_id>/', views.detail, name='detail'),
    ## 댓글 작성
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    ## 질문 작성
    path('question/create/', views.question_create, name='question_create'),
    ## 댓글 삭제
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

team/urls.py
# team/urls.py

from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
    path('', views.index, name='index'),  # 기본 URL에 대해 views.index 호출
    
]

welfare1/urls.py
from django.urls import path
from . import views

app_name = 'welfare1'

urlpatterns = [
    path('', views.index, name='index'),
    path('policy_main', views.policy_main, name='policy_main'),
    path('policy/01/', views.policy_01, name='policy_01'),
    path('policy/02/', views.policy_02, name='policy_02'),
    path('policy/03/', views.policy_03, name='policy_03'),
    path('policy/04/', views.policy_04, name='policy_04'),
    path('policy/05/', views.policy_05, name='policy_05'),
    path('policy/06/', views.policy_06, name='policy_06'),
    path('policy/07/', views.policy_07, name='policy_07'),
    path('policy/08/', views.policy_08, name='policy_08'),
    path('policy/09/', views.policy_09, name='policy_09'),
    path('policy/10/', views.policy_10, name='policy_10'),
    path('policy/11/', views.policy_11, name='policy_11'),
    path('policy/12/', views.policy_12, name='policy_12'),
    path('protect', views.protect, name='protect'),
    path('home', views.home, name='home'),
    path('welfare_detail', views.welfare_detail, name='welfare_detail'),
    path('senior_class', views.senior_class, name='senior_class'),
    path('nursing', views.nursing, name='nursing'),

]

templates/base.html
{%  load static %}
<!doctype html>
<html lang="en">
<head>
    <link rel="icon" href="{% static 'image/favicon/white/favicon.ico' %}" type="image/x-icon" sizes="16x16">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    
    <!--<link rel="apple-touch-icon" href="/media/favicon/white/favicon.png"/> -->
    <title>sunset</title>
</head>
<body style="background-color:rgb(255, 255, 255)">
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

templates/navbar.html
<style>


    @font-face {
        font-family: 'MaruBuri-Regular';
        src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10-21@1.0/MaruBuri-Regular.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }

    body .navbar {
        font-size: initial !important;
    }

    .navbar {
        background-color: rgb(255, 255, 255) !important;
        border-bottom: 0.5px solid #000000 !important;
        backdrop-filter: blur(9px);
    }

    .navbar-brand {
        color: #000000 !important;
        font-size: 33px !important;
        padding-left: 55px;
        font-family: 'MaruBuri-Regular' !important;
    }

    .navbar-nav {
        padding-right: 50px;
    }

    .nav-item {
        margin-right: 20px;
        font-size: initial !important;
    }

    .navbar-nav .nav-item .nav-link {
        color: #000000 !important; /* 글씨 색상 */
        transition: color 0.3s, background-color 0.3s; /* 색상 전환 효과를 부드럽게 */
        padding: 10px 15px !important;
        border-radius: 5px;
        font-family: 'MaruBuri-Regular' !important;
    }

    .navbar-nav .nav-item .nav-link:hover,
    .navbar-nav .nav-item .nav-link:focus,
    .navbar-nav .nav-item .nav-link:active {
        color: #000000;
        background-color: transparent;
        border: 1px solid #000000;
        font-family: 'MaruBuri-Regular' !important;
    }
</style>

<!-- 네비게이션바 -->
<nav class="navbar fixed-top navbar-expand-xl navbar-dark bg-dark border-bottom">
    <div class="container-fluid">
        <b><a class="navbar-brand" href="{% url 'main:index' %}"><span>善世: SUNSET</span></a></b>
        
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:index' %}">MAIN</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'team:index' %}">팀 소개</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'welfare1:index' %}">복지시설</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'qna:index' %}"><span>QnA</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<br><br>