config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  # 관리자 URL 패턴 정의
    # path('user/', include('user.urls')),  # user 앱의 URL 패턴
    # path('common/', include('common.urls')),  # common 앱의 URL 패턴
    path('qna/', include('qna.urls')),  # qna 앱의 URL 패턴
    path('welfare1/', include('welfare1.urls')),  # welfare1 앱의 URL 패턴
    #path('main/', include('main.urls')),  # main 앱의 URL 패턴
    path('team/', include('team.urls')),  # team 앱의 URL 패턴
    path('', include('main.urls')),  # 루트 URL을 main 앱으로 포워딩
]

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
    ## 질문 불러오기
    path('', views.index, name='index'),
    ## 질문 상세 조회
    path('<int:question_id>/', views.detail, name='detail'),
    ## 댓글 작성
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    ## 질문 작성
    path('question/create/', views.question_create, name='question_create'),
    ## 댓글 삭제
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

welfare1/urls.py
from django.urls import path
from . import views

app_name = 'welfare1'

urlpatterns = [
    path('', views.index, name='index'),
    path('policy_main', views.policy_main, name='policy_main'),
    path('policy/01/', views.policy_01, name='policy_01'),
    path('policy/02/', views.policy_02, name='policy_02'),
    path('policy/03/', views.policy_03, name='policy_03'),
    path('policy/04/', views.policy_04, name='policy_04'),
    path('policy/05/', views.policy_05, name='policy_05'),
    path('policy/06/', views.policy_06, name='policy_06'),
    path('policy/07/', views.policy_07, name='policy_07'),
    path('policy/08/', views.policy_08, name='policy_08'),
    path('policy/09/', views.policy_09, name='policy_09'),
    path('policy/10/', views.policy_10, name='policy_10'),
    path('policy/11/', views.policy_11, name='policy_11'),
    path('policy/12/', views.policy_12, name='policy_12'),
    path('protect', views.protect, name='protect'),
    path('home', views.home, name='home'),
    path('welfare_detail', views.welfare_detail, name='welfare_detail'),
    path('senior_class', views.senior_class, name='senior_class'),
    path('nursing', views.nursing, name='nursing'),

]

welfare1/models.py
from django.db import models

# Create your models here.

welfare1/views.py
# welfare_app/views.py

from django.shortcuts import render

def index(request):
    return render(request, 'welfare1/condense_main.html')



def page2(request):
    return render(request, 'welfare1/page2.html')
from django.shortcuts import render


def policy_main(request) :
    return render(request, 'welfare1/policy_main.html')


def policy_01(request):
    return render(request, 'welfare1/01.html')

def policy_02(request):
    return render(request, 'welfare1/02.html')

def policy_03(request):
    return render(request, 'welfare1/03.html')

def policy_04(request):
    return render(request, 'welfare1/04.html')

def policy_05(request):
    return render(request, 'welfare1/05.html')

def policy_06(request):
    return render(request, 'welfare1/06.html')

def policy_07(request):
    return render(request, 'welfare1/07.html')

def policy_08(request):
    return render(request, 'welfare1/08.html')

def policy_09(request):
    return render(request, 'welfare1/09.html')

def policy_10(request):
    return render(request, 'welfare1/10.html')

def policy_11(request):
    return render(request, 'welfare1/11.html')

def policy_12(request):
    return render(request, 'welfare1/12.html')

def protect(request):
    return render(request, 'welfare1/13.html')
def home(request):
    return render(request, 'welfare1/14.html')


def welfare_detail(request):
    return render(request, 'welfare1/15.html')

def senior_class(request):
    return render(request, 'welfare1/16.html')
def nursing(request):
    return render(request, 'welfare1/17.html')

templates/welfare1/02.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>복지 정책 안내</title>
    <link rel="stylesheet" href="{% static 'css/welfare1/Mstyle.css' %}">
    <style>
        /* 텍스트에 적용할 글꼴 */
        body, h1, h2, p, a, th, td {
            font-family: 'MaruBuri-Regular';
            font-weight: bold; /* MaruBuri-Regular 글꼴*/
            
        }
    </style>
</head>    
<body>
    <!-- Header -->
    
    
    <div class="container">
        <!-- 왼쪽 섹션: 사진 크게 표시 -->
        <div class="left-section">
            <img src="{% static 'image/policy_02.jpg' %}" alt="노원1종합사회복지관" width="650">
        </div>

        <!-- 오른쪽 섹션: 복지기관 정보 및 표 -->
        <div class="right-section">
            <h1>노원1종합사회복지관</h1>
            <p>소재지: 월계로 327(월계3동)</p>
            <p>연락처: 949-0700</p>
            <br>
            <h2>홈페이지 링크</h2>
            <a href="https://www.nowon.or.kr/" target="_blank">클릭하세요</a>
            <br>
            <br>
            <h2>저소득어르신 급식지원 정책</h2>
            <p>경로식당 : 결식우려가 있는 만 60세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>도시락배달 : 결식우려가 있는 만 65세 이상 거동불편 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>밑반찬배달 : 결식우려가 있는 만 65세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <table>
                <tr>
                    <th>경로식당</th>
                    <th>도시락배달</th>
                    <th>밑반찬배달</th>
                </tr>
                <tr>
                    <th>O</th>
                    <th>O</th>
                    <th>O</th>
                </tr>
            </table>
        </div>
    </div>
</body>
{% endblock %}

templates/welfare1/03.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>복지 정책 안내</title>
    <link rel="stylesheet" href="{% static 'css/welfare1/Mstyle.css' %}">
    <style>
        /* 텍스트에 적용할 글꼴 */
        body, h1, h2, p, a, th, td {
            font-family: 'MaruBuri-Regular';
            font-weight: bold; /* MaruBuri-Regular 글꼴*/
            
        }
    </style>
</head>    


<body>
    <div class="container">
        <div class="left-section">
            <img src="{% static 'image/policy_03_.jpg' %}" alt="마들종합사회복지관" width="650">
        </div>
        <div class="right-section">
            <h1>마들종합사회복지관</h1>
            <p>소재지: 동일로210길(중계2.3동)</p>
            <p>연락처: 971-8387</p>
            <br>
            <h2>홈페이지 링크</h2>
            <a href="https://madeul.org/" target="_blank">클릭하세요</a>
            <br>
            <br>
            <h2>저소득어르신 급식지원 정책</h2>
            <p>경로식당 : 결식우려가 있는 만 60세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>도시락배달 : 결식우려가 있는 만 65세 이상 거동불편 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>밑반찬배달 : 결식우려가 있는 만 65세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <table>
                <tr>
                    <th>경로식당</th>
                    <th>도시락배달</th>
                    <th>밑반찬배달</th>
                </tr>
                <tr>
                    <th>O</th>
                    <th>O</th>
                    <th>O</th>
                </tr>
            </table>
        </div>
    </div>
</body>
{% endblock %}

templates/welfare1/04.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>복지 정책 안내</title>
    <link rel="stylesheet" href="{% static 'css/welfare1/Mstyle.css' %}">
    <style>
        /* 텍스트에 적용할 글꼴 */
        body, h1, h2, p, a, th, td {
            font-family: 'MaruBuri-Regular';
            font-weight: bold; /* MaruBuri-Regular 글꼴*/
            
        }
    </style>
</head>


<body>
    <div class="container">
        <div class="left-section">
            <img src="{% static 'image/policy_04.jpg' %}" alt="북부종합사회복지관" width="650">
        </div>
        <div class="right-section">
            <h1>북부종합사회복지관</h1>
            <p>소재지: 동일로245길(상계1동)</p>
            <p>연락처: 934-7711</p>
            <br>
            <h2>홈페이지 링크</h2>
            <a href="http://www.bookboo.or.kr/" target="_blank">클릭하세요</a>
            <br>
            <br>
            <h2>저소득어르신 급식지원 정책</h2>
            <p>경로식당 : 결식우려가 있는 만 60세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>도시락배달 : 결식우려가 있는 만 65세 이상 거동불편 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>밑반찬배달 : 결식우려가 있는 만 65세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <table>
                <tr>
                    <th>경로식당</th>
                    <th>도시락배달</th>
                    <th>밑반찬배달</th>
                </tr>
                <tr>
                    <th>O</th>
                    <th>O</th>
                    <th>O</th>
                </tr>
            </table>
        </div>
    </div>
</body>
{% endblock %}

templates/welfare1/05.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>복지 정책 안내</title>
    <link rel="stylesheet" href="{% static 'css/welfare1/Mstyle.css' %}">
    <style>
        /* 텍스트에 적용할 글꼴 */
        body, h1, h2, p, a, th, td {
            font-family: 'MaruBuri-Regular';
            font-weight: bold; /* MaruBuri-Regular 글꼴*/
            
        }
    </style>
</head>    
    <!-- Header -->

<body>
    <div class="container">
        <!-- 왼쪽 섹션: 사진 크게 표시 -->
        <div class="left-section">
            <img src="{% static 'image/policy_05_.jpg' %}" alt="북부종합사회복지관" width="650">
        </div>

        <!-- 오른쪽 섹션: 복지기관 정보 및 표 -->
        <div class="right-section">
            <h1>상계종합사회복지관</h1>
            <p>소재지: 덕릉로115나길25(상계3,4동)</p>
            <p>연락처: 951-9930</p>
            <br>
            <h2>홈페이지 링크</h2>
            <a href="http://www.sanggyebokji.or.kr/" target="_blank">클릭하세요</a>
            <br>
            <br>
            <h2>저소득어르신 급식지원 정책</h2>
            <p>경로식당 : 결식우려가 있는 만 60세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>도시락배달 : 결식우려가 있는 만 65세 이상 거동불편 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>밑반찬배달 : 결식우려가 있는 만 65세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <table>
                <tr>
                    <th>경로식당</th>
                    <th>도시락배달</th>
                    <th>밑반찬배달</th>
                </tr>
                <tr>
                    <th>O</th>
                    <th>O</th>
                    <th>O</th>
                </tr>
                
                
            </table>
        </div>
    </div>
</body>
{% endblock %}

templates/welfare1/06.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>복지 정책 안내</title>
    <link rel="stylesheet" href="{% static 'css/welfare1/Mstyle.css' %}">
    <style>
        /* 텍스트에 적용할 글꼴 */
        body, h1, h2, p, a, th, td {
            font-family: 'MaruBuri-Regular';
            font-weight: bold; /* MaruBuri-Regular 글꼴*/
            
        }
    </style>
</head>


<body>
    <div class="container">
        <div class="left-section">
            <img src="{% static 'image/policy_06_.jpg' %}" alt="월계종합사회복지관" width="650">
        </div>
        <div class="right-section">
            <h1>월계종합사회복지관</h1>
            <p>소재지: 초안산로1길51(월계2동)</p>
            <p>연락처: 999-4211</p>
            <br>
            <h2>홈페이지 링크</h2>
            <a href="http://www.wwc.or.kr/" target="_blank">클릭하세요</a>
            <br>
            <br>
            <h2>저소득어르신 급식지원 정책</h2>
            <p>경로식당 : 결식우려가 있는 만 60세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>도시락배달 : 결식우려가 있는 만 65세 이상 거동불편 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>밑반찬배달 : 결식우려가 있는 만 65세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <table>
                <tr>
                    <th>경로식당</th>
                    <th>도시락배달</th>
                    <th>밑반찬배달</th>
                </tr>
                <tr>
                    <th>O</th>
                    <th>O</th>
                    <th>O</th>
                </tr>
            </table>
        </div>
    </div>
</body>
{% endblock %}

templates/welfare1/08.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>복지 정책 안내</title>
    <link rel="stylesheet" href="{% static 'css/welfare1/Mstyle.css' %}">
    <style>
        /* 텍스트에 적용할 글꼴 */
        body, h1, h2, p, a, th, td {
            font-family: 'MaruBuri-Regular';
            font-weight: bold; /* MaruBuri-Regular 글꼴*/
            
        }
    </style>
</head>


<body>
    <div class="container">
        <div class="left-section">
            <img src="{% static 'image/policy_08_.png' %}" alt="평화종합사회복지관" width="650">
        </div>
        <div class="right-section">
            <h1>평화종합사회복지관</h1>
            <p>소재지: 노원로331(중계2.3동)</p>
            <p>연락처: 949-0123</p>
            <br>
            <h2>홈페이지 링크</h2>
            <a href="https://www.pyunghwa.or.kr/" target="_blank">클릭하세요</a>
            <br>
            <br>
            <h2>저소득어르신 급식지원 정책</h2>
            <p>경로식당 : 결식우려가 있는 만 60세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>도시락배달 : 결식우려가 있는 만 65세 이상 거동불편 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>밑반찬배달 : 결식우려가 있는 만 65세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <table>
                <tr>
                    <th>경로식당</th>
                    <th>도시락배달</th>
                    <th>밑반찬배달</th>
                </tr>
                <tr>
                    <th>O</th>
                    <th>O</th>
                    <th>O</th>
                </tr>
            </table>
        </div>
    </div>
</body>
{% endblock %}

templates/welfare1/10.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>복지 정책 안내</title>
    <link rel="stylesheet" href="{% static 'css/welfare1/Mstyle.css' %}">
    <style>
        /* 텍스트에 적용할 글꼴 */
        body, h1, h2, p, a, th, td {
            font-family: 'MaruBuri-Regular';
            font-weight: bold; /* MaruBuri-Regular 글꼴*/
            
        }
    </style>
</head>


<body>
    <div class="container">
        <div class="left-section">
            <img src="{% static 'image/policy_10_.png' %}" alt="시립노원노인종합복지관" width="650">
        </div>
        <div class="right-section">
            <h1>시립노원노인종합복지관</h1>
            <p>소재지: 노원로16길15(하계1동)</p>
            <p>연락처: 948-8540</p>
            <br>
            <h2>홈페이지 링크</h2>
            <a href="https://www.nowonsenior.or.kr/" target="_blank">클릭하세요</a>
            <br>
            <br>
            <h2>저소득어르신 급식지원 정책</h2>
            <p>경로식당 : 결식우려가 있는 만 60세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>도시락배달 : 결식우려가 있는 만 65세 이상 거동불편 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <p>밑반찬배달 : 결식우려가 있는 만 65세 이상 저소득 어르신(국민기초생활수급자, 차상위 등)</p>
            <table>
                <tr>
                    <th>경로식당</th>
                    <th>도시락배달</th>
                    <th>밑반찬배달</th>
                </tr>
                <tr>
                    <th>O</th>
                    <th></th>
                    <th>O</th>
                </tr>
            </table>
        </div>
    </div>
</body>
{% endblock %}

templates/welfare1/condense_main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>급식정책소개</title>
    <link rel="stylesheet" href="{% static 'css/welfare1/Mstyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/welfare1/intro.css' %}">
    <style>
        /* 이미지와 텍스트를 감싸는 div의 스타일 */
        .image-container {
            position: relative; /* 이미지와 텍스트를 포함하는 div의 위치를 지정하기 위해 설정 */
            width: 20%; /* 이미지 컨테이너의 너비를 23%로 설정하여 한 줄에 3개의 이미지가 나타나도록 함 */
            margin: 5%; /* 이미지 컨테이너 사이의 간격을 설정 */
            float: left; /* 이미지 컨테이너를 왼쪽으로 정렬하여 한 줄에 3개씩 표시 */
            max-width : 700px;
            min-width : 700px;
            
        }

        /* 텍스트의 스타일 */
        .image-text {
            position: absolute; /* 텍스트의 위치를 지정하기 위해 설정 */
            bottom: 0; /* 이미지 아래에 위치하도록 설정 */
            left: 0; /* 왼쪽 정렬 */
            width: 105%; /* 부모 요소의 너비에 맞춤 */
            background-color: black; /* 텍스트 배경색 및 투명도 설정 */
            padding: 3px; /* 텍스트 주변 여백 설정 */
            text-align: center; /* 텍스트 가운데 정렬 */
            font-size: 36px; /* 텍스트 크기 설정 */
            color: white; /* 텍스트 색상 설정 */
            max-width : 700px;
            min-width : 700px;
        } 

        
        
        /* 추가한 @font-face 규칙 */
        @font-face {
            font-family: 'MaruBuri-Regular';
            src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10-21@1.0/MaruBuri-Regular.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }
        
        /* 복지정책소개 페이지 전체에 MaruBuri-Regular 글꼴을 적용 */
        html, body {
            font-family: 'MaruBuri-Regular', sans-serif;
        }
    </style>
</head>
<body>
	
    <div class="image-container">
        <a href="{% url 'welfare1:policy_main' %}">
            <img src ="{% static 'image/bap.jpg' %}" alt="공릉종합사회복지관" width="710" height="500">
        </a>
        <div class="image-text">급식 지원</div>
    </div>
    
        <div class="image-container">
        <a href="{% url 'welfare1:protect' %}">
            <img src="https://cdn.pixabay.com/photo/2015/07/01/09/27/silhouettes-827423_1280.jpg" alt="주야간 보호서비스" width="700" height="500">
        </a>
        <div class="image-text">주야간 보호서비스</div>
    </div>
    
        <div class="image-container">
        <a href="{% url 'welfare1:home' %}">
            <img src="{% static 'image/home.jpg' %}" alt="노인요양 공동생활가정" width="700" height="500">
        </a>
        <div class="image-text">노인요양 공동생활가정</div>
    </div>

    <div class="image-container">
        <a href="{% url 'welfare1:welfare_detail' %}">
            <img src="{% static 'image/welfare_detail.jpg' %}" alt="방문요양 지원시설" width="700" height="500">
        </a>
        <div class="image-text">방문 요양 지원시설</div>
    </div>

    <div class="image-container">
        <a href="{% url 'welfare1:senior_class' %}">
            <img src="{% static 'image/visitingnursing.jpg' %}" alt="방문간호" width="700" height="500">
        </a>
        <div class="image-text">방문간호</div>
    </div>

    <div class="image-container">
        <a href="{% url 'welfare1:nursing' %}">
            <img src="{% static 'image/nursing.jpg' %}" alt="노인요양시설" width="700" height="500">
        </a>
        <div class="image-text">노인요양시설</div>
    </div>
  </body>
</html>
{% endblock %}

templates/welfare1/policy_main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/welfare1/Mstyle.css' %}">
    <style>
        /* 이미지와 텍스트를 감싸는 div의 스타일 */
        .image-container {
            position: relative; /* 이미지와 텍스트를 포함하는 div의 위치를 지정하기 위해 설정 */
            width: 30%; /* 이미지 컨테이너의 너비를 23%로 설정하여 한 줄에 3개의 이미지가 나타나도록 함 */
            margin: 7%; /* 이미지 컨테이너 사이의 간격을 설정 */
            float: left; /* 이미지 컨테이너를 왼쪽으로 정렬하여 한 줄에 3개씩 표시 */
            font-family: 'MaruBuri-Regular'; /* MaruBuri-Regular 글꼴  */
        }

        /* 텍스트의 스타일 */
        .image-text {
            position: absolute; /* 텍스트의 위치를 지정하기 위해 설정 */
            bottom: -10; /* 이미지 아래에 위치하도록 설정 */
            left: 0; /* 왼쪽 정렬 */
            width: 105.15%; /* 부모 요소의 너비에 맞춤 */
            background-color: black; /* 텍스트 배경색 및 투명도 설정 */
            padding: 3px; /* 텍스트 주변 여백 설정 */
            text-align: center; /* 텍스트 가운데 정렬 */
            font-size: 40px; /* 텍스트 크기 설정 */
            color: white; /* 텍스트 색상 설정 */
            font-family: 'MaruBuri-Regular'; /* MaruBuri-Regular 글꼴  */
        }
    </style>
</head>
<body>
    <div class="image-container">
        <a href="{% url 'welfare1:policy_01' %}">
            <img src="{% static 'image/policy_01.png' %}" alt="공릉종합사회복지관" width="600" height="300">
        </a>
        <div class="image-text">공릉종합사회복지관</div>
    </div>
    
    <div class="image-container">
        <a href="{% url 'welfare1:policy_02' %}">
            <img src="{% static 'image/policy_02.jpg' %}" alt="노원1종합사회복지관" width="600" height="300">
        </a>
        <div class="image-text">노원1종합사회복지관</div>
    </div>
    
    <div class="image-container">
        <a href="{% url 'welfare1:policy_03' %}">
            <img src="{% static 'image/policy_03_.jpg' %}" alt="마들종합사회복지관" width="600" height="300">
        </a>
        <div class="image-text">마들종합사회복지관</div>
    </div>
    
    <div class="image-container">
        <a href="{% url 'welfare1:policy_04' %}">
            <img src="{% static 'image/policy_04.jpg' %}" alt="북부종합사회복지관" width="600" height="300">
        </a>
        <div class="image-text">북부종합사회복지관</div>
    </div>
    
    <div class="image-container">
        <a href="{% url 'welfare1:policy_05' %}">
            <img src="{% static 'image/policy_05_.jpg' %}" alt="상계종합사회복지관" width="600" height="300">
        </a>
        <div class="image-text">상계종합사회복지관</div>
    </div>
    
    <div class="image-container">
        <a href="{% url 'welfare1:policy_06' %}">
            <img src="{% static 'image/policy_06_.jpg' %}" alt="월계종합사회복지관" width="600" height="300">
        </a>
        <div class="image-text">월계종합사회복지관</div>
    </div>
    
    <div class="image-container">
        <a href="{% url 'welfare1:policy_07' %}">
            <img src="{% static 'image/policy_07_.png' %}" alt="중계종합사회복지관" width="600" height="300">
        </a>
        <div class="image-text">중계종합사회복지관</div>
    </div>
    
    <div class="image-container">
        <a href="{% url 'welfare1:policy_08' %}">
            <img src="{% static 'image/policy_08_.png' %}" alt="평화종합사회복지관" width="600" height="300">
        </a>
        <div class="image-text">평화종합사회복지관</div>
    </div>
    
    <div class="image-container">
        <a href="{% url 'welfare1:policy_09' %}">
            <img src="{% static 'image/policy_09_.png' %}" alt="하계종합사회복지관" width="600" height="300">
        </a>
        <div class="image-text">하계종합사회복지관</div>
    </div>
    
    <div class="image-container">
        <a href="{% url 'welfare1:policy_10' %}">
            <img src="{% static 'image/policy_10_.png' %}" alt="시립노원노인종합복지관" width="600" height="300">
        </a>
        <div class="image-text">시립노원노인종합복지관</div>
    </div>
    
    <div class="image-container">
        <a href="{% url 'welfare1:policy_11' %}">
            <img src="{% static 'image/policy_11_.png' %}" alt="공릉노인복지관" width="600" height="300">
        </a>
        <div class="image-text">공릉노인복지관</div>
    </div>
    
    <div class="image-container">
        <a href="{% url 'welfare1:policy_12' %}">
            <img src="{% static 'image/policy_12_.png' %}" alt="월계노인복지관" width="600" height="300">
        </a>
        <div class="image-text">월계노인복지관</div>
    </div>
</body>
{% endblock %}